services:
  caldron:
    image: com.timmciver/caldron:latest
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - FILE_STORE_URL=http://localhost:3000/blobs
      - SPARQL_URL=http://fuseki:3030/ds

  fuseki:
    image: atomgraph/fuseki:4.7.0
    user: root # otherwise the fuseki user does not have permissions to the mounted folder which is owner by root
    expose:
      - 3030
    volumes:
      - ./data/fuseki:/fuseki/databases

  rainbow-hash:
    image: com.timmciver/rainbow-hash:latest
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ./data/rainbow-hash:/some/path # FIXME

  proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/http/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html/static
      - ./caldron.timmciver.com.crt:/etc/nginx/ssl/server.crt
      - ./caldron.timmciver.com.key:/etc/nginx/ssl/server.key
#    network_mode: host
    depends_on:
      - caldron

  # fuseki:
  #   image: 
